# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iv39IttUNJezxvV6bXsspOcEZn4aDYLz
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

st.set_page_config(page_title="K-Means Clustering", layout="wide")

st.title("K-Means Clustering on Income Dataset")

uploaded_file = st.file_uploader("Upload income.csv", type=["csv"])

if uploaded_file is not None:

    df = pd.read_csv(uploaded_file)

    st.subheader("Dataset")
    st.dataframe(df)

    st.subheader("Original Data")

    fig, ax = plt.subplots(figsize=(6,4))
    ax.scatter(df["Age"], df["Income($)"])
    ax.set_xlabel("Age")
    ax.set_ylabel("Income($)")
    st.pyplot(fig)

    # Number of clusters
    k = st.slider("Select Number of Clusters", 2, 10, 3)

    # KMeans before scaling
    km = KMeans(n_clusters=k, random_state=42)
    df["cluster"] = km.fit_predict(df[["Age", "Income($)"]])

    st.subheader("Cluster Centers (Before Scaling)")
    st.write(km.cluster_centers_)

    fig, ax = plt.subplots(figsize=(6,4))

    colors = ['red', 'green', 'blue', 'orange', 'purple',
              'black', 'cyan', 'magenta', 'brown', 'pink']

    for i in range(k):
        cluster = df[df.cluster == i]
        ax.scatter(cluster["Age"], cluster["Income($)"],
                   color=colors[i % len(colors)],
                   label=f"Cluster {i}")

    ax.scatter(km.cluster_centers_[:,0],
               km.cluster_centers_[:,1],
               color='yellow',
               marker='*',
               s=250,
               label='Centroid')

    ax.set_xlabel("Age")
    ax.set_ylabel("Income($)")
    ax.legend()

    st.pyplot(fig)

    # Scaling
    scaler = MinMaxScaler()

    scaled_df = df.copy()

    scaled_df["Age"] = scaler.fit_transform(scaled_df[["Age"]])
    scaled_df["Income($)"] = scaler.fit_transform(
        scaled_df[["Income($)"]]
    )

    st.subheader("Scaled Dataset")
    st.dataframe(scaled_df)

    # KMeans after scaling
    km = KMeans(n_clusters=k, random_state=42)
    scaled_df["cluster"] = km.fit_predict(
        scaled_df[["Age", "Income($)"]]
    )

    st.subheader("Cluster Centers (After Scaling)")
    st.write(km.cluster_centers_)

    fig, ax = plt.subplots(figsize=(6,4))

    for i in range(k):
        cluster = scaled_df[scaled_df.cluster == i]
        ax.scatter(cluster["Age"],
                   cluster["Income($)"],
                   color=colors[i % len(colors)],
                   label=f"Cluster {i}")

    ax.scatter(km.cluster_centers_[:,0],
               km.cluster_centers_[:,1],
               color='yellow',
               marker='*',
               s=250,
               label='Centroid')

    ax.set_xlabel("Scaled Age")
    ax.set_ylabel("Scaled Income")
    ax.legend()

    st.pyplot(fig)

    # Elbow Method
    st.subheader("Elbow Method")

    sse = []

    K = range(1, 11)

    for i in K:
        model = KMeans(n_clusters=i, random_state=42)
        model.fit(scaled_df[["Age", "Income($)"]])
        sse.append(model.inertia_)

    fig, ax = plt.subplots(figsize=(6,4))
    ax.plot(K, sse, marker='o')
    ax.set_xlabel("Number of Clusters (K)")
    ax.set_ylabel("Sum of Squared Error")
    ax.set_title("Elbow Method")

    st.pyplot(fig)

else:
    st.info("Please upload income.csv to continue.")