# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iv39IttUNJezxvV6bXsspOcEZn4aDYLz
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

st.set_page_config(page_title="K-Means Clustering", layout="wide")

st.title("K-Means Clustering on Income Dataset")

uploaded_file = st.file_uploader("Upload income.csv", type=["csv"])

if uploaded_file is not None:

    # Read dataset
    df = pd.read_csv(uploaded_file)

    # Remove extra spaces from column names
    df.columns = df.columns.str.strip()

    # Check required columns
    required_cols = ["Age", "Income($)"]

    if not all(col in df.columns for col in required_cols):
        st.error(
            f"Dataset must contain the columns: {required_cols}\n\n"
            f"Found columns: {list(df.columns)}"
        )
        st.stop()

    # Keep only required columns if desired
    df = df.copy()

    # Convert to numeric
    df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
    df["Income($)"] = pd.to_numeric(df["Income($)"], errors="coerce")

    # Remove missing values
    df.dropna(subset=["Age", "Income($)"], inplace=True)

    if len(df) < 2:
        st.error("Dataset must contain at least two valid rows.")
        st.stop()

    st.subheader("Dataset")
    st.dataframe(df)

    # Original Scatter Plot
    st.subheader("Original Data")

    fig, ax = plt.subplots(figsize=(6,4))
    ax.scatter(df["Age"], df["Income($)"], color="blue")
    ax.set_xlabel("Age")
    ax.set_ylabel("Income($)")
    st.pyplot(fig)

    # Slider
    max_k = min(10, len(df))
    default_k = min(3, max_k)

    k = st.slider(
        "Select Number of Clusters",
        min_value=2,
        max_value=max_k,
        value=default_k
    )

    # ------------------------
    # KMeans Before Scaling
    # ------------------------
    km = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    df["cluster"] = km.fit_predict(df[["Age", "Income($)"]])

    st.subheader("Cluster Centers (Before Scaling)")
    st.write(pd.DataFrame(
        km.cluster_centers_,
        columns=["Age", "Income($)"]
    ))

    colors = [
        "red","green","blue","orange","purple",
        "cyan","magenta","brown","pink","black"
    ]

    fig, ax = plt.subplots(figsize=(6,4))

    for i in range(k):
        cluster = df[df.cluster == i]
        ax.scatter(
            cluster["Age"],
            cluster["Income($)"],
            color=colors[i % len(colors)],
            label=f"Cluster {i}",
            s=70
        )

    ax.scatter(
        km.cluster_centers_[:,0],
        km.cluster_centers_[:,1],
        marker="*",
        s=250,
        color="yellow",
        edgecolors="black",
        label="Centroids"
    )

    ax.set_xlabel("Age")
    ax.set_ylabel("Income($)")
    ax.legend()

    st.pyplot(fig)

    st.subheader("Clustered Dataset")
    st.dataframe(df)

    # ------------------------
    # Scaling
    # ------------------------
    scaler = MinMaxScaler()

    scaled_df = df.copy()

    scaled_df[["Age", "Income($)"]] = scaler.fit_transform(
        scaled_df[["Age", "Income($)"]]
    )

    st.subheader("Scaled Dataset")
    st.dataframe(scaled_df)

    # ------------------------
    # KMeans After Scaling
    # ------------------------
    km_scaled = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    scaled_df["cluster"] = km_scaled.fit_predict(
        scaled_df[["Age", "Income($)"]]
    )

    st.subheader("Cluster Centers (After Scaling)")
    st.write(pd.DataFrame(
        km_scaled.cluster_centers_,
        columns=["Scaled Age", "Scaled Income"]
    ))

    fig, ax = plt.subplots(figsize=(6,4))

    for i in range(k):
        cluster = scaled_df[scaled_df.cluster == i]
        ax.scatter(
            cluster["Age"],
            cluster["Income($)"],
            color=colors[i % len(colors)],
            label=f"Cluster {i}",
            s=70
        )

    ax.scatter(
        km_scaled.cluster_centers_[:,0],
        km_scaled.cluster_centers_[:,1],
        marker="*",
        s=250,
        color="yellow",
        edgecolors="black",
        label="Centroids"
    )

    ax.set_xlabel("Scaled Age")
    ax.set_ylabel("Scaled Income")
    ax.legend()

    st.pyplot(fig)

    # ------------------------
    # Elbow Method
    # ------------------------
    st.subheader("Elbow Method")

    sse = []

    for i in range(1, max_k + 1):
        model = KMeans(
            n_clusters=i,
            random_state=42,
            n_init=10
        )
        model.fit(scaled_df[["Age", "Income($)"]])
        sse.append(model.inertia_)

    fig, ax = plt.subplots(figsize=(6,4))
    ax.plot(range(1, max_k + 1), sse, marker="o")
    ax.axvline(k, color="red", linestyle="--", label=f"K={k}")
    ax.set_xlabel("Number of Clusters")
    ax.set_ylabel("SSE")
    ax.set_title("Elbow Method")
    ax.legend()

    st.pyplot(fig)

else:
    st.info("Please upload income.csv to continue.")
